- name: Invoke custom ansible module
  hosts: localhost
  tasks:
    - name: Invoke hello module
      hello: message='Custom Ansible Module!'

    - name: Invoke add module
      add: firstInput=100.5 secondInput=200.5 
      register: output

    - debug: var=output
