- name: Remove all existing containers
  hosts: localhost
  pre_tasks:
    - name: Delete all containers
      shell: docker rm -f $(docker ps -aq)
      ignore_errors: True

    - name: Install Python package installer
      apt: name=python-pip state=latest update_cache=yes

    - name: Install docker-py python module
      shell: pip install docker-py

  tasks:
    - name: Provision Ubuntu containers
      docker_container: 
         name: "ubuntu{{item}}"
         hostname: "ubuntu{{item}}"
         image: "tektutor/ansible-ubuntu"
         state: started 
         ports:
           - "800{{item}}:80"
           - "200{{item}}:22"
      with_sequence: start=1 end=3

    - name: Provision CentOS containers
      docker_container: 
         name: "centos{{item}}"
         hostname: "centos{{item}}"
         image: "tektutor/ansible-centos"
         state: started 
         ports:
           - "900{{item}}:80"
           - "300{{item}}:22"
      with_sequence: start=1  end=3

#  post_tasks:
#    - name: Invoke install nginx playbook
#      shell: ansible-playbook install-nginx-refactor-1.yml 
