- name: Build image
  hosts: localhost
  tasks:
     - name: Build Jenkins slave docker image
       docker_image:
          name: "tektutor/jenkins-slave"
          dockerfile: Dockerfile
          state: build
          path: "."
