---
- name: Install apache2 in Ubuntu
  when: ansible_distribution == "Ubuntu"
  apt: name=apache2 state=latest update_cache=yes

- name: Install Extra Packages for Enterprise Linux in CentOS
  when: ansible_distribution == "CentOS"
  yum: name=epel-release state=latest 

- name: Install httpd in CentOS
  when: ansible_distribution == "CentOS"
  yum: name=httpd state=latest 
...
